#
# Learn more about this Gitpod configuration file in the documentation at https://www.gitpod.io/docs/configuration
#
ports:
  - port: 3000
    onOpen: open-preview
    visibility: public

  - port: 3010
    onOpen: open-preview
    visibility: public

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks
# gp url docs: https://www.gitpod.io/docs/release-notes/2019-02-15/february-2019#gp-url
# ports docs: https://www.gitpod.io/docs/config-ports
tasks:
  - init: pnpm install

  - name: Site
    command: |
      export HMR_HOST=`gp url 3000`
      pnpm site
    openMode: split-left

  - name: Parts
    command: |
      export HMR_HOST=`gp url 3010`
      pnpm parts
    openMode: split-right
    
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false

vscode:
  extensions:
    # Svelte
    - svelte.svelte-vscode
    - fivethree.vscode-svelte-snippets
    # Styles
    - voorjaar.windicss-intellisense
    - antfu.iconify
    # Code Quality
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
